[package]
name = "newrelic-unofficial-rust"
version = "0.1.0"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
attohttpc = { version = "0.15.0", features = ["json"] }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
flate2 = "1.0.16"
anyhow = "1.0.31"
thiserror = "1.0.20"
# url = "2.1.1"
